FROM golang:alpine AS builder
WORKDIR /build
COPY go.mod go.sum ./
COPY vendor/ vendor/
COPY . .
RUN CGO_ENABLED=0 go build -mod=vendor \
    -ldflags "-s -w" \
    -o bin/victoria-logs \
    ./app/victoria-logs/

FROM alpine:3.20
RUN apk add --no-cache ca-certificates
COPY --from=builder /build/bin/victoria-logs /usr/local/bin/victoria-logs
ENTRYPOINT ["victoria-logs"]
